using System;

namespace AdventOfCode.Y2025;

class SplashScreenImpl : SplashScreen {

    public void Show() {

        var color = Console.ForegroundColor;
        Write(0xcc00, false, "           ▄█▄ ▄▄█ ▄ ▄ ▄▄▄ ▄▄ ▄█▄  ▄▄▄ ▄█  ▄▄ ▄▄▄ ▄▄█ ▄▄▄\n           █▄█ █ █ █ █ █▄█ █ █ █   █ █ █▄ ");
            Write(0xcc00, false, " █  █ █ █ █ █▄█\n           █ █ █▄█ ▀▄▀ █▄▄ █ █ █▄  █▄█ █   █▄ █▄█ █▄█ █▄▄  0x0000 | 2025\n           ");
            Write(0xcc00, false, " \n                    ");
            Write(0xffffff, false, "____ ..'  .'   ");
            Write(0xffff66, true, "*     ");
            Write(0xffffff, false, "'        . ");
            Write(0xff9900, false, "<");
            Write(0xffffff, false, "o             \n           ________/");
            Write(0x999999, false, "O___");
            Write(0xffffff, false, "\\__________");
            Write(0xff0000, false, "|");
            Write(0xffffff, false, "_________________O______  ");
            Write(0xcccccc, false, " 1 ");
            Write(0xffff66, false, "**\n            ");
            Write(0x32211a, false, "' ");
            Write(0x999999, false, "_______");
            Write(0xaabbcc, false, "||");
            Write(0x999999, false, "_________ ");
            Write(0x32211a, false, "'       .   ..      .             \n           .  ");
            Write(0x999999, false, "| ");
            Write(0x9b715b, false, "_");
            Write(0xbb66ff, false, "@");
            Write(0x9b715b, false, "__ ");
            Write(0xaabbcc, false, "|| ");
            Write(0x9b715b, false, "_");
            Write(0x66ff, false, "o");
            Write(0x9b715b, false, "_  ");
            Write(0xff0000, false, "'.");
            Write(0x999999, false, "|_ _________________________   ");
            Write(0xcccccc, false, " 2 ");
            Write(0xffff66, false, "**\n              ");
            Write(0x999999, false, "|_");
            Write(0xff0000, false, "&");
            Write(0x999999, false, "_");
            Write(0xffff66, false, "%");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "||");
            Write(0x999999, false, "_");
            Write(0x66ff, false, "o");
            Write(0xff9900, false, "o");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "^");
            Write(0x9b715b, false, "=");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "[ ");
            Write(0x999999, false, "\\|");
            Write(0xff00, false, "..'  ");
            Write(0xaabbcc, false, "_    ");
            Write(0xff0000, false, ".");
            Write(0x666666, false, ". ");
            Write(0xff0000, false, ".");
            Write(0x666666, false, ". ");
            Write(0xff0000, false, ".");
            Write(0x666666, false, ".     ");
            Write(0x999999, false, "|        \n              ");
            Write(0x32211a, false, "'    '  '. . '    ");
            Write(0x999999, false, "\\_");
            Write(0xaabbcc, false, "]");
            Write(0x999999, false, "__");
            Write(0x9b715b, false, "--");
            Write(0xaabbcc, false, "|_|");
            Write(0x999999, false, "___");
            Write(0xaabbcc, false, "[]");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "[]");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "[]");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "//");
            Write(0x999999, false, "_|   ");
            Write(0xcccccc, false, " 3 ");
            Write(0xffff66, false, "**\n           ");
            Write(0x32211a, false, ". . '  .  . ' ' '''            ");
            Write(0x999999, false, "____________");
            Write(0xaabbcc, false, "//");
            Write(0x999999, false, "___        \n           __________________________  ");
            Write(0xaa7744, false, "...");
            Write(0x999999, false, "| ");
            Write(0xffffff, false, "\\ ");
            Write(0xff0000, false, "'");
            Write(0xff00, false, "'");
            Write(0xff0000, false, "'");
            Write(0xff00, false, "'");
            Write(0xff0000, false, "'");
            Write(0xff00, false, "' ");
            Write(0xaabbcc, false, "// ");
            Write(0xffffff, false, "@@");
            Write(0x999999, false, "|   ");
            Write(0xcccccc, false, " 4 ");
            Write(0xffff66, false, "**\n           ");
            Write(0x999999, false, "|");
            Write(0x9900, false, "_  ");
            Write(0xffffff, false, "___ ");
            Write(0x999999, false, "| ");
            Write(0xaabbcc, false, ".--.  ");
            Write(0x9900, false, "()   ()  ");
            Write(0x999999, false, "|");
            Write(0xaa7744, false, ".' ..");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "[#]");
            Write(0x999999, false, "_");
            Write(0xffffff, false, "@@");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "//");
            Write(0x999999, false, "_");
            Write(0xffffff, false, "@@@");
            Write(0x999999, false, "|        \n           |");
            Write(0x9900, false, "_\\");
            Write(0x999999, false, "_");
            Write(0xffffff, false, "|");
            Write(0xff9900, true, "^");
            Write(0xffffff, false, "|");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "]");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "|");
            Write(0x9b715b, false, "==");
            Write(0xaabbcc, false, "|");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0xaa7744, false, "...'                      ");
            Write(0xcccccc, false, " 5 ");
            Write(0xffff66, false, "**\n            ");
            Write(0x9900, false, "|| ");
            Write(0x32211a, false, ".");
            Write(0x666666, false, " ____________                                      \n           ");
            Write(0x999999, false, "_");
            Write(0x9900, false, "||");
            Write(0x999999, false, "__");
            Write(0x666666, false, "/            \\_                               ");
            Write(0xcccccc, false, " 6 ");
            Write(0xffff66, false, "**\n           ");
            Write(0x999999, false, "|");
            Write(0xff00, false, "^");
            Write(0xbb66ff, false, "@ ");
            Write(0x999999, false, "|");
            Write(0x333333, false, "   1  2  3    |                                    \n           ");
            Write(0x999999, false, "|");
            Write(0xff0000, false, "&");
            Write(0xffff66, false, "%");
            Write(0xaaaa, false, ";");
            Write(0xaabbcc, false, "]");
            Write(0x333333, false, "__[]_[]_[]__<>|                               ");
            Write(0x666666, false, " 7\n                                                                   \n                             ");
            Write(0x666666, false, "                                  8\n                                                                ");
            Write(0x666666, false, "   \n                                                               9\n                               ");
            Write(0x666666, false, "                                    \n                                                              1");
            Write(0x666666, false, "0\n                                                                   \n                              ");
            Write(0x666666, false, "                                11\n                                                                 ");
            Write(0x666666, false, "  \n                                                              12\n           \n");
            
        Console.ForegroundColor = color;
        Console.WriteLine();
    }

    private static void Write(int rgb, bool bold, string text){
       Console.Write($"\u001b[38;2;{(rgb>>16)&255};{(rgb>>8)&255};{rgb&255}{(bold ? ";1" : "")}m{text}");
    }
}