using System;

namespace AdventOfCode.Y2025;

class SplashScreenImpl : SplashScreen {

    public void Show() {

        var color = Console.ForegroundColor;
        Write(0xcc00, false, "           ▄█▄ ▄▄█ ▄ ▄ ▄▄▄ ▄▄ ▄█▄  ▄▄▄ ▄█  ▄▄ ▄▄▄ ▄▄█ ▄▄▄\n           █▄█ █ █ █ █ █▄█ █ █ █   █ █ █▄ ");
            Write(0xcc00, false, " █  █ █ █ █ █▄█\n           █ █ █▄█ ▀▄▀ █▄▄ █ █ █▄  █▄█ █   █▄ █▄█ █▄█ █▄▄  λy.2025\n            \n    ");
            Write(0xcc00, false, "       ");
            Write(0xffffff, false, "'        ____ ' .    '' ");
            Write(0xffff66, true, "* ");
            Write(0xffffff, false, ".''.  .' . ... ");
            Write(0xff9900, false, "<");
            Write(0xffffff, false, "o '   .       \n           ________/");
            Write(0x999999, false, "O___");
            Write(0xffffff, false, "\\__________");
            Write(0xff0000, false, "|");
            Write(0xffffff, false, "_________________O______  ");
            Write(0xcccccc, false, " 1 ");
            Write(0xffff66, false, "**\n              ");
            Write(0x999999, false, "_______");
            Write(0xaabbcc, false, "||");
            Write(0x999999, false, "_________            ");
            Write(0x32211a, false, "'.' '          .       \n           '  ");
            Write(0x999999, false, "| ");
            Write(0x9b715b, false, "_");
            Write(0xbb66ff, false, "@");
            Write(0x9b715b, false, "__ ");
            Write(0xaabbcc, false, "|| ");
            Write(0x9b715b, false, "_");
            Write(0x66ff, false, "o");
            Write(0x9b715b, false, "_  ");
            Write(0xff0000, false, "'.");
            Write(0x999999, false, "|_ _________________________   ");
            Write(0xcccccc, false, " 2 ");
            Write(0xffff66, false, "**\n              ");
            Write(0x999999, false, "|_");
            Write(0xff0000, false, "&");
            Write(0x999999, false, "_");
            Write(0xffff66, false, "%");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "||");
            Write(0x999999, false, "_");
            Write(0x66ff, false, "o");
            Write(0xff9900, false, "o");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "^");
            Write(0x9b715b, false, "=");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "[ ");
            Write(0x999999, false, "\\|");
            Write(0xff00, false, "..'  ");
            Write(0xaabbcc, false, "_    ");
            Write(0xff0000, false, ".");
            Write(0x666666, false, ". ");
            Write(0xff0000, false, ".");
            Write(0x666666, false, ". ");
            Write(0xff0000, false, ".");
            Write(0x666666, false, ".     ");
            Write(0x999999, false, "|        \n           ");
            Write(0x32211a, false, "'     .     '   .    ");
            Write(0x999999, false, "\\_");
            Write(0xaabbcc, false, "]");
            Write(0x999999, false, "__");
            Write(0x9b715b, false, "--");
            Write(0xaabbcc, false, "|_|");
            Write(0x999999, false, "___");
            Write(0xaabbcc, false, "[]");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "[]");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "[]");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "//");
            Write(0x999999, false, "_|   ");
            Write(0xcccccc, false, " 3 ");
            Write(0xffff66, false, "**\n            ");
            Write(0x32211a, false, ".'  .     .    '  '   '''..   ");
            Write(0x999999, false, "____________");
            Write(0xaabbcc, false, "//");
            Write(0x999999, false, "___        \n           __________________________  ");
            Write(0xaa7744, false, "...");
            Write(0x999999, false, "| ");
            Write(0xffffff, false, "\\ ");
            Write(0xff0000, false, "'");
            Write(0xff00, false, "'");
            Write(0xff0000, false, "'");
            Write(0xff00, false, "'");
            Write(0xff0000, false, "'");
            Write(0xff00, false, "' ");
            Write(0xaabbcc, false, "// ");
            Write(0xffffff, false, "@@");
            Write(0x999999, false, "|   ");
            Write(0xcccccc, false, " 4 ");
            Write(0xffff66, false, "**\n           ");
            Write(0x999999, false, "|");
            Write(0x9900, false, "_  ");
            Write(0xffffff, false, "___ ");
            Write(0x999999, false, "| ");
            Write(0xaabbcc, false, ".--.  ");
            Write(0x9900, false, "()   ()  ");
            Write(0x999999, false, "|");
            Write(0xaa7744, false, ".' ..");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "[#]");
            Write(0x999999, false, "_");
            Write(0xffffff, false, "@@");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "//");
            Write(0x999999, false, "_");
            Write(0xffffff, false, "@@@");
            Write(0x999999, false, "|        \n           |");
            Write(0x9900, false, "_\\");
            Write(0x999999, false, "_");
            Write(0xffffff, false, "|");
            Write(0xff9900, true, "^");
            Write(0xffffff, false, "|");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "]");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "|");
            Write(0x9b715b, false, "==");
            Write(0xaabbcc, false, "|");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0x9b715b, false, "T");
            Write(0x999999, false, "_");
            Write(0xaa7744, false, "...'    ");
            Write(0x32211a, false, ".  .'.'  ' .      ");
            Write(0xcccccc, false, " 5 ");
            Write(0xffff66, false, "**\n            ");
            Write(0x9900, false, "||   ");
            Write(0x999999, false, "____________  ");
            Write(0x32211a, false, "' ");
            Write(0x999999, false, "_______________________           \n           _");
            Write(0x9900, false, "||");
            Write(0x999999, false, "__/");
            Write(0xff0000, false, "'...' ");
            Write(0xff00, false, "'...' ");
            Write(0x999999, false, "\\_  |");
            Write(0xff0000, false, ".     ");
            Write(0x9b715b, false, "|");
            Write(0xff0000, false, "~    ");
            Write(0xff00, false, ".'");
            Write(0xff0000, false, "'.    .");
            Write(0x999999, false, "|      ");
            Write(0xcccccc, false, " 6 ");
            Write(0xffff66, false, "**\n           ");
            Write(0x999999, false, "|");
            Write(0xff00, false, "^");
            Write(0xbb66ff, false, "@ ");
            Write(0x999999, false, "|   ");
            Write(0xaabbcc, false, "1  2  3 ");
            Write(0x9900, false, "() ");
            Write(0x999999, false, "|  | ");
            Write(0xff0000, false, "'..'");
            Write(0x9b715b, false, "/ \\");
            Write(0xff00, false, "'..'    ");
            Write(0xff0000, false, "'..' ");
            Write(0x999999, false, "|");
            Write(0x666666, false, "____       \n           ");
            Write(0x999999, false, "|");
            Write(0xff0000, false, "&");
            Write(0xffff66, false, "%");
            Write(0xaaaa, false, ";");
            Write(0xaabbcc, false, "]");
            Write(0x999999, false, "__");
            Write(0xaabbcc, false, "[]");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "[]");
            Write(0x999999, false, "_");
            Write(0xaabbcc, false, "[]");
            Write(0x999999, false, "__");
            Write(0xffff66, false, "<>");
            Write(0x999999, false, "|  |    ");
            Write(0x9b715b, false, "|H_");
            Write(0x66ff, false, "/");
            Write(0x9b715b, false, "|");
            Write(0x66ff, false, "\\   ");
            Write(0xaabbcc, false, "\\\\\\\\\\\\  ");
            Write(0x999999, false, "|");
            Write(0x666666, false, " | |  ");
            Write(0xcccccc, false, " 7 ");
            Write(0xffff66, false, "**\n                             '...");
            Write(0x999999, false, "|");
            Write(0xffff66, false, "<>");
            Write(0x9900, false, "__");
            Write(0x9b715b, false, "|H");
            Write(0x9900, false, "__");
            Write(0x9b715b, false, "|");
            Write(0x9900, false, "_");
            Write(0x66ff, false, "\\");
            Write(0x9900, false, "__");
            Write(0xaabbcc, false, "|");
            Write(0x9900, false, "_____");
            Write(0xaabbcc, false, "|");
            Write(0x9900, false, "_");
            Write(0x9b715b, false, "[");
            Write(0x666666, false, "_O_|       \n                                                         |    ");
            Write(0xcccccc, false, " 8 ");
            Write(0xffff66, false, "**\n           ");
            Write(0x333333, false, "                             _________________O__       \n                                        |  ");
            Write(0x333333, false, "[  ]          | |  ");
            Write(0x666666, false, " 9\n           ");
            Write(0x333333, false, "                             ]_____-/_-/_-/___|_|       \n                                           ");
            Write(0x333333, false, "                   ");
            Write(0x666666, false, "10\n                                                                   \n                             ");
            Write(0x666666, false, "                                 11\n                                                                ");
            Write(0x666666, false, "   \n                                                              12\n           \n");
            
        Console.ForegroundColor = color;
        Console.WriteLine();
    }

    private static void Write(int rgb, bool bold, string text){
       Console.Write($"\u001b[38;2;{(rgb>>16)&255};{(rgb>>8)&255};{rgb&255}{(bold ? ";1" : "")}m{text}");
    }
}