
using System;

namespace AdventOfCode.Y2018 {

    class SplashScreenImpl : AdventOfCode.SplashScreen {

        public void Show() {

            var color = Console.ForegroundColor;
            Write(0xffff66, "\n  __   ____  _  _  ____  __ _  ____     __  ____     ___  __  ____  ____         \n / _\\ (    \\/ )( ");
            Write(0xffff66, "\\(  __)(  ( \\(_  _)   /  \\(  __)   / __)/  \\(    \\(  __)        \n/    \\ ) D (\\ \\/ / ) _) /    /  )( ");
            Write(0xffff66, "   (  O )) _)   ( (__(  O )) D ( ) _)         \n\\_/\\_/(____/ \\__/ (____)\\_)__) (__)    \\__/(__)     \\");
            Write(0xffff66, "___)\\__/(____/(____)  2018\n\n                ");
            Write(0xcccccc, ".         .         .        .        .       ");
            Write(0x888888, "25 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n            ");
            Write(0xcccccc, ".        .         .        .       ");
            Write(0x886655, "\\  /      ");
            Write(0xcccccc, ".   ");
            Write(0x888888, "24 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                         ");
            Write(0xcccccc, ".         .         ");
            Write(0x886655, "\\_\\_\\|_/__/      ");
            Write(0x888888, "23 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                  ");
            Write(0xcccccc, ".         .            .  ");
            Write(0xff0000, "o");
            Write(0x886655, "-_/");
            Write(0xcccccc, ".()");
            Write(0x886655, "__-------  ");
            Write(0x888888, "22 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n              ");
            Write(0xcccccc, ".       .            ");
            Write(0xffff66, "*         ");
            Write(0x886655, "\\____            ");
            Write(0x888888, "21 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                          ");
            Write(0xcccccc, ".       ");
            Write(0xff0000, "|");
            Write(0xcccccc, "\\|            \\_");
            Write(0x886655, "\\_ ");
            Write(0xcccccc, "___  /  ");
            Write(0x888888, "20 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                  ");
            Write(0xcccccc, ".               |");
            Write(0xff0000, "\\|              ");
            Write(0x886655, "/ |   ||   ");
            Write(0x888888, "19 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n             ");
            Write(0xcccccc, ".           ");
            Write(0x66ff, "_________");
            Write(0xff0000, "|");
            Write(0xcccccc, "\\|");
            Write(0x66ff, "_________    ");
            Write(0x886655, "/  |   ||   ");
            Write(0x888888, "18 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                 ");
            Write(0x66ff, "___-----  ");
            Write(0xcccccc, "###########  ##### ");
            Write(0x66ff, "-----___        ");
            Write(0x888888, "17 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n           ");
            Write(0x66ff, "___---  ");
            Write(0xcccccc, "###  #####    #########  #####     ");
            Write(0x66ff, "---___  ");
            Write(0x888888, "16 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                 ");
            Write(0xcccccc, ") ))          ) )                    __");
            Write(0xff0000, "__    ");
            Write(0x888888, "15 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n              ");
            Write(0xff0000, ".-");
            Write(0xcccccc, "(");
            Write(0xff0000, "-");
            Write(0xcccccc, "((");
            Write(0xff0000, "-.     ");
            Write(0x9900, ".--");
            Write(0xcccccc, "(");
            Write(0x9900, "-");
            Write(0xcccccc, "(");
            Write(0x9900, "-.                  ");
            Write(0xff0000, "/ ");
            Write(0xcccccc, "_");
            Write(0xff0000, "\\ ");
            Write(0xcccccc, "\\   ");
            Write(0x888888, "14 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n              ");
            Write(0xff0000, "'------'_    ");
            Write(0x9900, "'------'_                ");
            Write(0xff0000, "|");
            Write(0xcccccc, "/|  |/");
            Write(0xff0000, "|  ");
            Write(0x888888, "13 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n              ");
            Write(0xff0000, "|      | )   ");
            Write(0x9900, "|      | )               ");
            Write(0xcccccc, "|_|  ");
            Write(0xff0000, "|/");
            Write(0xcccccc, "|  ");
            Write(0x888888, "12 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n              ");
            Write(0xff0000, "|      |/    ");
            Write(0x9900, "|      |/                     ");
            Write(0xcccccc, "|/");
            Write(0xff0000, "|  ");
            Write(0x888888, "11 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n              ");
            Write(0xff0000, "'------'     ");
            Write(0x9900, "'------'                      ");
            Write(0xff0000, "|/");
            Write(0xcccccc, "|  ");
            Write(0x888888, "10 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                                              ");
            Write(0xff0000, "_     __   ");
            Write(0xcccccc, "|/");
            Write(0xff0000, "|  ");
            Write(0x888888, " 9 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                   ");
            Write(0xff0000, ".---_             _       ");
            Write(0x880000, "| ");
            Write(0xff0000, "|\\__");
            Write(0x880000, "/");
            Write(0xff0000, "_/)  |/");
            Write(0xcccccc, "|  ");
            Write(0x888888, " 8 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                  ");
            Write(0xff0000, "/ ");
            Write(0x880000, "/ ");
            Write(0xff0000, "/\\|      ");
            Write(0x999999, "__   ");
            Write(0x880000, ") ");
            Write(0xff0000, ")__   ");
            Write(0x880000, "_|");
            Write(0xff0000, "_|     /   ");
            Write(0xcccccc, "|/");
            Write(0xff0000, "|  ");
            Write(0x888888, " 7 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n                ");
            Write(0xff0000, "/ ");
            Write(0x880000, "/ | ");
            Write(0xff0000, "\\ ");
            Write(0xffff66, "*    ");
            Write(0x999999, "/ / \\ ");
            Write(0x880000, "( ");
            Write(0xff0000, "(   \\_");
            Write(0x880000, "/");
            Write(0xff0000, "_/      /    |/");
            Write(0xcccccc, "|  ");
            Write(0x888888, " 6 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n               ");
            Write(0xff0000, "/  ");
            Write(0x880000, "/  \\ ");
            Write(0xff0000, "\\    ");
            Write(0x999999, "| | \\/  ");
            Write(0x880000, "\\_");
            Write(0xff0000, "\\____________/     ");
            Write(0xcccccc, "|_|  ");
            Write(0x888888, " 5 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n              ");
            Write(0xff0000, "/ ");
            Write(0x880000, "/  / \\  ");
            Write(0xff0000, "\\    ");
            Write(0x999999, "\\_\\______X_____X_____X_,         ");
            Write(0x888888, " 4 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n            ");
            Write(0xcccccc, "./~~~~~~~~~~~\\.                                   ");
            Write(0x888888, " 3 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n           ");
            Write(0xcccccc, "( .\",^. -\". '.~ )                                  ");
            Write(0x888888, " 2 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n           ");
            Write(0xcccccc, "_'~~~~~~~~~~~~~'_________ ___ __ _  _   _    _     ");
            Write(0x888888, " 1 ");
            Write(0xfff66, "*");
            Write(0xffff66, "*\n           \n");
            
            Console.ForegroundColor = color;
            Console.WriteLine();
        }

       private static void Write(int rgb, string text){
           Console.Write($"\u001b[38;2;{(rgb>>16)&255};{(rgb>>8)&255};{rgb&255}m{text}");
       }
    }
}