
using System;

namespace AdventOfCode.Y2017 {

    class SplashScreenImpl : SplashScreen {

        public void Show() {

            var color = Console.ForegroundColor;
            Write(0xcc00, false, "\n       ▄█▄ ▄▄█ ▄ ▄ ▄▄▄ ▄▄ ▄█▄  ▄▄▄ ▄█  ▄▄ ▄▄▄ ▄▄█ ▄▄▄\n       █▄█ █ █ █ █ █▄█ █ █ █   █ █ █▄  █  █ █");
            Write(0xcc00, false, " █ █ █▄█\n       █ █ █▄█ ▀▄▀ █▄▄ █ █ █▄  █▄█ █   █▄ █▄█ █▄█ █▄▄  /^2017$/\n\n           ");
            Write(0x999999, false, "|O|  ");
            Write(0xcccccc, false, "      Naughty      |        Nice         ");
            Write(0x999999, false, "|O|       \n           |O|  ");
            Write(0xcccccc, false, "-------------------+-------------------  ");
            Write(0x999999, false, "|O|       \n           |O|  ");
            Write(0xcccccc, false, "The Easter Bunny   | encse               ");
            Write(0x999999, false, "|O|       \n           |O|  ");
            Write(0xcccccc, false, "osteele            | Gabriel Moita       ");
            Write(0x999999, false, "|O|       \n           |O|  ");
            Write(0xcccccc, false, "Greg Fuller        | seejohnrun          ");
            Write(0x999999, false, "|O|       \n           |O|  ");
            Write(0xcccccc, false, "Galen Elias        | jozefvaclavik       ");
            Write(0x999999, false, "|O|       \n           |O|  ");
            Write(0xcccccc, false, "Sean Sartell       | Matt Wood           ");
            Write(0x999999, false, "|O|       \n           ");
            Write(0xcccccc, false, ".-----------------------------------------------.       \n           | ");
            Write(0x666666, false, "┌┬────────────");
            Write(0xaaaaaa, false, "[─]");
            Write(0x666666, false, "─────");
            Write(0x990099, false, "┤[]├");
            Write(0x666666, false, "─");
            Write(0x9900, false, "oTo");
            Write(0x666666, false, "─┐┌──");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "────────┐ ");
            Write(0xcccccc, false, "|  25 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "=├──────────────────┐o────");
            Write(0xff9900, false, "∧∧∧");
            Write(0x666666, false, "──┘│o┐└─");
            Write(0x9900, false, "oTo");
            Write(0x666666, false, "─");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "┌─┘ ");
            Write(0xcccccc, false, "|  24 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "V└───┐┌───");
            Write(0xff0000, false, "┤|├");
            Write(0x666666, false, "───o┌──┤┌─");
            Write(0xff9900, false, "∧∧∧");
            Write(0x666666, false, "──────┴─┘");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "─");
            Write(0xff9900, false, "∧∧∧");
            Write(0x666666, false, "─┘└─o ");
            Write(0xcccccc, false, "|  23 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "├┬─┬┴┴┴┴┐┌─");
            Write(0x9900, false, "oTo");
            Write(0x666666, false, "───┘o─┘│");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "───────────┐└────────┐ ");
            Write(0xcccccc, false, "|  22 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "=└─┤    ├└───┐┌──────┘└────");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "┌┬───o└─────────┤ ");
            Write(0xcccccc, false, "|  21 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "┌──┤ 512├────┤│┌──┐┌──┐");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "───┘=└──┬───────────┘ ");
            Write(0xcccccc, false, "|  20 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "├──┤  PB├────┘└┤o─┴┘o─┘└───────");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "│o─────");
            Write(0x66ff, false, "|(");
            Write(0x666666, false, "───┐ ");
            Write(0xcccccc, false, "|  19 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "└──┴┬┬┬┬┴───");
            Write(0x66ff, false, "|(");
            Write(0x666666, false, "─┘");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "────────────┐┌┘└───────────┤ ");
            Write(0xcccccc, false, "|  18 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "┌───────");
            Write(0x66ff, false, "|(");
            Write(0x666666, false, "─────┐└───");
            Write(0x66ff, false, "|(");
            Write(0x666666, false, "──┐┌┬─o│└┐┌──────────");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "│ ");
            Write(0xcccccc, false, "|  17 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "├──");
            Write(0xff9900, false, "∧∧∧");
            Write(0x666666, false, "─┐o────┬┬┴┴┴┬────┬┘=└──┴─┘│V");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "────────┘= ");
            Write(0xcccccc, false, "|  16 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "└─────o└────┐├┤   ├────┘┌───────┴┘└────────");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "o ");
            Write(0xcccccc, false, "|  15 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "┌───");
            Write(0xff9900, false, "∧∧∧");
            Write(0x666666, false, "─────┘└┤   ├─────┴──o");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "┬┴┴┴┴┬───────┐└┐ ");
            Write(0xcccccc, false, "|  14 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "└───┬┴┴┴┴┴┬───┤   ├o─┬─o");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "───┘┤   i├──");
            Write(0x9900, false, "oTo");
            Write(0x666666, false, "─┬┘┌┘ ");
            Write(0xcccccc, false, "|  13 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "┌───┤     ├───┴┬┬┬┴──┘┌─┘┌───┤   3├─");
            Write(0x990099, false, "┤[]├");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "└─┤V ");
            Write(0xcccccc, false, "|  12 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "└┐o┬┤    A├──────────┬┘┌─┴o");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "─┤   8├──┬──┘┌o└┤ ");
            Write(0xcccccc, false, "|  11 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "V├┐└┤    L├o─────────┘┌┴o┌─┘o┤   6├──┘┌");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "o┴──┘ ");
            Write(0xcccccc, false, "|  10 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "├┘└─┤    U├─");
            Write(0xaaaaaa, false, "[─]");
            Write(0x666666, false, "───────┘");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "┐└───┴┬┬┬┬┴───┘└────┐ ");
            Write(0xcccccc, false, "|   9 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "└o");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "─┤     ├────────────┘└──────────");
            Write(0x990099, false, "┤[]├");
            Write(0x9900, false, "oTo");
            Write(0x666666, false, "──┤ ");
            Write(0xcccccc, false, "|   8 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "┌─┘o┴┬┬┬┬┬┴───────");
            Write(0xaaaaaa, false, "[─]");
            Write(0x666666, false, "──────────────────┐┌──");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "= ");
            Write(0xcccccc, false, "|   7 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "├─────┘o──┬┬─");
            Write(0xff0000, false, "┤|├");
            Write(0x666666, false, "───");
            Write(0x66ff, false, "|(");
            Write(0x666666, false, "─o");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "──────────────┐└┴─o└┐ ");
            Write(0xcccccc, false, "|   6 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "└────────┐=└─────");
            Write(0xaaaaaa, false, "[─]");
            Write(0x666666, false, "──┐└─────");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "o───────┴─────┤ ");
            Write(0xcccccc, false, "|   5 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "┌───────o│┌──────┬────┴──o");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "─┐└─────────┬─┐┌o│ ");
            Write(0xcccccc, false, "|   4 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "├────────┘└───┐o─┘");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "┬──────┘o┴─────────┐=┌┘├─┘ ");
            Write(0xcccccc, false, "|   3 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "└────");
            Write(0xff9900, false, "∧∧∧");
            Write(0x666666, false, "──────┤┌──┘=┌───────────");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "┌───o└─┘┌┘o┐ ");
            Write(0xcccccc, false, "|   2 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "| ");
            Write(0x666666, false, "o───");
            Write(0x66ff, false, "|(");
            Write(0x666666, false, "────────┘└────┴o");
            Write(0xffff66, true, "*");
            Write(0x666666, false, "─────────┘└───────┴──┘ ");
            Write(0xcccccc, false, "|   1 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcccccc, false, "'-----------------------------------------------'       \n           \n");
            
            Console.ForegroundColor = color;
            Console.WriteLine();
        }

       private static void Write(int rgb, bool bold, string text){
           Console.Write($"\u001b[38;2;{(rgb>>16)&255};{(rgb>>8)&255};{rgb&255}{(bold ? ";1" : "")}m{text}");
       }
    }
}