
using System;

namespace AdventOfCode.Y2017 {

    class SplashScreenImpl : AdventOfCode.SplashScreen {

        public void Show() {

            var color = Console.ForegroundColor;
            Write(ConsoleColor.Yellow, "\n  __   ____  _  _  ____  __ _  ____     __  ____     ___  __  ____  ____         \n / _\\ (    \\/ )( ");
            Write(ConsoleColor.Yellow, "\\(  __)(  ( \\(_  _)   /  \\(  __)   / __)/  \\(    \\(  __)        \n/    \\ ) D (\\ \\/ / ) _) /    /  )( ");
            Write(ConsoleColor.Yellow, "   (  O )) _)   ( (__(  O )) D ( ) _)         \n\\_/\\_/(____/ \\__/ (____)\\_)__) (__)    \\__/(__)     \\");
            Write(ConsoleColor.Yellow, "___)\\__/(____/(____)  2017\n\n           ");
            Write(ConsoleColor.DarkGray, "|O|        Naughty      |        Nice         |O|       \n           |O|  -------------------+-------");
            Write(ConsoleColor.DarkGray, "------------  |O|       \n           |O|  The Easter Bunny   | encse               |O|       \n       ");
            Write(ConsoleColor.DarkGray, "    |O|  mrisoli            | Csaba Okrona        |O|       \n           |O|  Róbert Bán         | Ma");
            Write(ConsoleColor.DarkGray, "te Borcsok        |O|       \n           |O|  akoskaaa           | szalai1             |O|       \n   ");
            Write(ConsoleColor.DarkGray, "        |O|  vigoo              | David Guerrero      |O|       \n           ");
            Write(ConsoleColor.Gray, ".-----------------------------------------------.       \n           | ");
            Write(ConsoleColor.DarkGray, "o┬─────────┐┌───────────────────────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───");
            Write(ConsoleColor.Red, "[─]");
            Write(ConsoleColor.DarkGray, "─┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "25 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌┘o───┬───o││┌──o");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "──────────");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "─────┘o──────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "24 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "├────┐└────┘│├┴┴┴┴┬───────────────────");
            Write(ConsoleColor.Cyan, "┤[]├");
            Write(ConsoleColor.DarkGray, "──");
            Write(ConsoleColor.Yellow, "* ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "23 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└───o└─");
            Write(ConsoleColor.Cyan, "┤[]├");
            Write(ConsoleColor.DarkGray, "┐└┤    ├");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "─────────");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "──────");
            Write(ConsoleColor.DarkCyan, "┤|├");
            Write(ConsoleColor.DarkGray, "────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "22 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌───");
            Write(ConsoleColor.Red, "[─]");
            Write(ConsoleColor.DarkGray, "────┴─┤   1├└──");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "───────────────────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "21 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "├─────┬┴┴┴┬─┐┤  A0├─┐┌──┬┐o───────┐");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───────┘= ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "20 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "│o────┤   ├o└┤  P7├─┘└o┌┘└────────┼┴┴┴┴┬────");
            Write(ConsoleColor.Yellow, "* ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "19 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─────┤   ├");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "─┤  L1├───┐└───┬┴┴┴┴┴┬┤    ├────┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "18 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "────┤   ├┘┌┴┬┬┬┬┴─┬o└─┐┌─┤     ├┤    ├───┐│ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "17 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "│└────┴┬┬┬┴");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "└───┬┴┴┴┴┴┬─┴┘┌┤    v├┤ x64├───┘│ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "16 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─┬┴┴┴┬─o");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┐└┐┌──┤     ├───┘┤    1├┴┬┬┬┬┴───o│ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "15 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "─┤ IR├──┘└─┘└─┐┤ PR2C├────┤    7├────┬─────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "14 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─┤ NN├────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┌──┘┤ 02-G├────┤     ├──┬┐└─────o ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "13 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "─┤ TE├────┤└───┴┬┬┬┬┬┴────┴┬┬┬┬┬┴─┐=└──");
            Write(ConsoleColor.Cyan, "┤[]├");
            Write(ConsoleColor.DarkGray, "┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "12 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└┐┤ ET├───┬┴┴┴┴┴┬─────────────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o───┴────────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "11 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌┘┤   ├───┤     ├┬───┐┌───────┘┌────────────");
            Write(ConsoleColor.Yellow, "* ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "10 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└┐└┬┬┬┴──┐┤hi   ├┘┌─┬┴┴┴┴┴┬────┘o──┐");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "──");
            Write(ConsoleColor.DarkCyan, "┤|├");
            Write(ConsoleColor.DarkGray, "──┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 9 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌┴──────o│┤ mom ├┐└─┤     ├───┐o┬──┘└───────");
            Write(ConsoleColor.Yellow, "* ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 8 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "├───────┐└┴┬┬┬┬┬┼┴──┤FLUX ├o──┴┐└──┬─┐V");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 7 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└──o┌───┴─────o│└─┬─┤CPTR ├");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "──┐└───┘o┴┘└────┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 6 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌───┘┌─────────┘");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┐=┌┴┬┬┬┬┬┴┘o─┴─────────────┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 5 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "├────┘┌─────────┘└┐└──┐┌───");
            Write(ConsoleColor.White, "∧∧∧");
            Write(ConsoleColor.DarkGray, "────────────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┌┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 4 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "=┌───┐└──┐o──┬────┘┌──┘└─────");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "──┐");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───────┘└o ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 3 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "V├─┐o┴───┘┌─┐└─────┘┌─");
            Write(ConsoleColor.White, "∧∧∧");
            Write(ConsoleColor.DarkGray, "────────┘└─────────");
            Write(ConsoleColor.Yellow, "* ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 2 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└┴o└──────┴o└───────┴o");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "────");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "──────────────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 1 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "'-----------------------------------------------'       \n           \n");
            
            Console.ForegroundColor = color;
            Console.WriteLine();
        }

       private static void Write(ConsoleColor color, string text){
           Console.ForegroundColor = color;
           Console.Write(text);
       }
    }
}