
using System;

namespace AdventOfCode.Y2020 {

    class SplashScreenImpl : SplashScreen {

        public void Show() {

            var color = Console.ForegroundColor;
            Write(0xcc00, false, "\n       ▄█▄ ▄▄█ ▄ ▄ ▄▄▄ ▄▄ ▄█▄  ▄▄▄ ▄█  ▄▄ ▄▄▄ ▄▄█ ▄▄▄\n       █▄█ █ █ █ █ █▄█ █ █ █   █ █ █▄  █  █ █");
            Write(0xcc00, false, " █ █ █▄█\n       █ █ █▄█ █▄█ █▄▄ █ █ █▄  █▄█ █   █▄ █▄█ █▄█ █▄▄  int y=2020;\n\n                       ");
            Write(0xcc00, false, "  ");
            Write(0xccccff, false, "..........");
            Write(0xff0000, false, "|");
            Write(0xccccff, false, "..........                ");
            Write(0xcccccc, false, " 1 ");
            Write(0xffff66, false, "**\n              ");
            Write(0xccccff, false, ".....'''''' ");
            Write(0xffffff, false, ".'  -  -  ");
            Write(0xcccccc, false, "\\");
            Write(0xffffff, false, "- .''");
            Write(0x333399, false, "~ ~ ");
            Write(0xccccff, false, "''''''.....     ");
            Write(0xcccccc, false, " 2 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xccccff, false, "''' ");
            Write(0x333399, false, "~ ~ ~ ~  ~ ");
            Write(0xffffff, false, "'.'. -   - ");
            Write(0xcccccc, false, "\\ ");
            Write(0xffffff, false, "-'':  ");
            Write(0x333399, false, "~ ~   ~  ~  ");
            Write(0xccccff, false, "'''  ");
            Write(0xcccccc, false, " 3 ");
            Write(0xffff66, false, "**\n            ");
            Write(0x333399, false, "~   ~  ~   ~ ~  ~ ");
            Write(0xffffff, false, "''..'''");
            Write(0xcccccc, false, "_[]");
            Write(0xffffff, false, ".'  ");
            Write(0x333399, false, "~    ~   ~ ~  ~   ");
            Write(0xcccccc, false, " 4 ");
            Write(0xffff66, false, "**\n           ");
            Write(0x333399, false, "~   ~ ~  ");
            Write(0xcc00, false, ".'. ");
            Write(0x333399, false, "~  ~  ~ ");
            Write(0xcccccc, false, "____/ ");
            Write(0xffffff, false, "''  ");
            Write(0x333399, false, "~  ~  ~");
            Write(0x666666, false, "  ~  ");
            Write(0x333399, false, "~    ~  ");
            Write(0xcccccc, false, " 5 ");
            Write(0xffff66, false, "**\n             ");
            Write(0x333399, false, "~    ~ ");
            Write(0xcc00, false, "''  ..");
            Write(0xcccccc, false, "_____/ ");
            Write(0x333399, false, "~   ~  ~  ~");
            Write(0x666666, false, "    _ ");
            Write(0x333399, false, "~");
            Write(0x666666, false, " _   O>    ");
            Write(0xcccccc, false, " 6 ");
            Write(0xffff66, false, "**\n            ");
            Write(0x333399, false, "~  ~ ~   ~ ");
            Write(0xcc00, false, ":");
            Write(0xcccccc, false, "[]");
            Write(0xcc00, false, "'.   ");
            Write(0x333399, false, "~   ~      ~");
            Write(0x666666, false, "  \\ / \\ / \\ /  ");
            Write(0x333399, false, "~   ");
            Write(0xcccccc, false, " 7 ");
            Write(0xffff66, false, "**\n                  ");
            Write(0x333399, false, "~     ");
            Write(0xcc00, false, "'.");
            Write(0xcccccc, false, "\\ ");
            Write(0x333399, false, "~        ~  ~");
            Write(0x666666, false, "   ~  ");
            Write(0x333399, false, "~      ~");
            Write(0x666666, false, "    ~  ");
            Write(0xcccccc, false, " 8 ");
            Write(0xffff66, false, "**\n            ");
            Write(0x333399, false, "~   ~      ~   ");
            Write(0xcccccc, false, "\\  ");
            Write(0x333399, false, "~   ");
            Write(0xcccccc, false, "____     ");
            Write(0x333399, false, "~      ~      ~    ");
            Write(0xcccccc, false, "17 ");
            Write(0xffff66, false, "**\n                  ");
            Write(0x333399, false, "~       ~ ");
            Write(0xcccccc, false, "\\____/ ");
            Write(0xcc00, false, ".''");
            Write(0xcccccc, false, "\\");
            Write(0xcc00, false, "'..    ");
            Write(0x333399, false, "~       ~    ");
            Write(0xcc00, false, ".  ");
            Write(0xcccccc, false, " 9 ");
            Write(0xffff66, false, "**\n               ");
            Write(0x333399, false, "~       ~  ");
            Write(0xcccccc, false, "__/\\ ");
            Write(0x333399, false, "~   ");
            Write(0xcc00, false, ".'");
            Write(0xffffff, false, "^ ");
            Write(0xcccccc, false, "[]");
            Write(0xcc00, false, ".'      ");
            Write(0x333399, false, "~  ~  ");
            Write(0xcc00, false, "..''   ");
            Write(0xcccccc, false, "16 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcc00, false, "...     ");
            Write(0x333399, false, "~");
            Write(0xcccccc, false, "_____/");
            Write(0x333399, false, "~   ");
            Write(0xcccccc, false, "\\    ");
            Write(0xcc00, false, ":");
            Write(0xffffff, false, "^ ");
            Write(0xcc00, false, ", :");
            Write(0xcccccc, false, "\\  ");
            Write(0x333399, false, "~       ");
            Write(0xcc00, false, ":''  , ");
            Write(0xffffff, false, "^  ");
            Write(0xcccccc, false, "18 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcc00, false, "###: ...");
            Write(0xcccccc, false, "/   ");
            Write(0x333399, false, "~      ~");
            Write(0xcccccc, false, "\\    ");
            Write(0xcc00, false, "'..'  ");
            Write(0xcccccc, false, "\\_______");
            Write(0x333399, false, "~ ");
            Write(0xcc00, false, "'. ,      ");
            Write(0xcccccc, false, "15 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcc00, false, ".'' .'");
            Write(0xcccccc, false, "[]");
            Write(0xcc00, false, "'.           ");
            Write(0xcccccc, false, "\\ ");
            Write(0x333399, false, "~       ~   ~   ");
            Write(0xcccccc, false, "\\  ");
            Write(0xcc00, false, ":  , ");
            Write(0xffffff, false, "^   ");
            Write(0xcccccc, false, "19 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcc00, false, "'...'##");
            Write(0xcccccc, false, "\\");
            Write(0xcc00, false, "##'.  ");
            Write(0x333399, false, "~    ~  ");
            Write(0xcccccc, false, "\\   ");
            Write(0x333399, false, "~            ");
            Write(0xcc00, false, ".");
            Write(0xcccccc, false, "\\");
            Write(0xcc00, false, "' ,  ");
            Write(0xffffff, false, "^ ^  ");
            Write(0xcccccc, false, "10 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcc00, false, "##### ,#");
            Write(0xcccccc, false, "\\");
            Write(0xcc00, false, "#.'           ");
            Write(0xcccccc, false, "\\   ");
            Write(0xcc00, false, ".       ");
            Write(0x333399, false, "~   ");
            Write(0xcc00, false, "'.");
            Write(0xcccccc, false, "[]  ");
            Write(0xcc00, false, ", ");
            Write(0xffffff, false, "^   ");
            Write(0xcccccc, false, "14 ");
            Write(0xffff66, false, "**\n           ");
            Write(0xcc00, false, "#,");
            Write(0x333333, false, "      ,");
            Write(0xcccccc, false, "\\");
            Write(0xcc00, false, "'.         ");
            Write(0x333399, false, "~  ");
            Write(0xcccccc, false, "\\");
            Write(0xcc00, false, "'',:  ");
            Write(0x333399, false, "~       ");
            Write(0xcccccc, false, "_/");
            Write(0xcc00, false, "'..  , ");
            Write(0xffffff, false, "^  ");
            Write(0x666666, false, "20\n              ~ ~   , ,");
            Write(0xcc00, false, "'");
            Write(0x666666, false, ".   ~     ");
            Write(0xcc00, false, ":");
            Write(0xcccccc, false, "[]");
            Write(0xcc00, false, "..'         ");
            Write(0xcccccc, false, "/ ");
            Write(0x333399, false, "~   ");
            Write(0xcc00, false, "''...  ");
            Write(0xcccccc, false, "11 ");
            Write(0xffff66, false, "**\n           ");
            Write(0x666666, false, "    ~ ~     , :         ");
            Write(0xcc00, false, "''");
            Write(0xcccccc, false, "\\__  ");
            Write(0x333399, false, "~     ");
            Write(0xcccccc, false, "/             13 ");
            Write(0xffff66, false, "**\n           ");
            Write(0x333333, false, "       ~ ~                ");
            Write(0x333399, false, "~  ");
            Write(0xcccccc, false, "\\__    /");
            Write(0x333399, false, "~      ~    \n                                           ");
            Write(0xcccccc, false, "\\__/               12 ");
            Write(0xffff66, false, "**\n                                           ");
            Write(0x333399, false, "~         ~    ~ \n                                      ~                     \n                     ");
            Write(0x333399, false, "                   ");
            Write(0xcc00, false, ". ..   .' ..       ");
            Write(0x333399, false, "~\n                                         ");
            Write(0xcc00, false, "'.            ");
            Write(0x333399, false, "~    \n           \n");
            
            Console.ForegroundColor = color;
            Console.WriteLine();
        }

       private static void Write(int rgb, bool bold, string text){
           Console.Write($"\u001b[38;2;{(rgb>>16)&255};{(rgb>>8)&255};{rgb&255}{(bold ? ";1" : "")}m{text}");
       }
    }
}