
using System;

namespace AdventOfCode2017 {

    class SplashScreen {

        public static void Show() {

            var color = Console.ForegroundColor;
            Write(ConsoleColor.Gray, "           .-----------------------------------------------.       \n           |                   ");
            Write(ConsoleColor.Gray, "                            |  ");
            Write(ConsoleColor.DarkGray, "25\n           ");
            Write(ConsoleColor.Gray, "|                                               |  ");
            Write(ConsoleColor.DarkGray, "24\n           ");
            Write(ConsoleColor.Gray, "|                                               |  ");
            Write(ConsoleColor.DarkGray, "23\n           ");
            Write(ConsoleColor.Gray, "|                                               |  ");
            Write(ConsoleColor.DarkGray, "22\n           ");
            Write(ConsoleColor.Gray, "|                                       ");
            Write(ConsoleColor.Yellow, "*       ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "21\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───┬┴┴┴┴┴┬──────");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "─────┐┌┐┌─");
            Write(ConsoleColor.Cyan, "┤[]├");
            Write(ConsoleColor.DarkCyan, "┤|├");
            Write(ConsoleColor.DarkGray, "─┘       ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "20 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "├──┐┤     ├┐┌───────────o└┘│└───┐┌──────────");
            Write(ConsoleColor.Yellow, "* ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "19 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─┐└┤     ├┘└─┬┴┴┴┬─────┬─o└──┬─┘└──┐");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "──────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "18 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "o─┴─┤     ├───┤ HA├────┐└─────┘┌────┘└───");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "─");
            Write(ConsoleColor.Yellow, "* ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "17 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌───┤ SRAM├───┤ AD├────┴─");
            Write(ConsoleColor.DarkCyan, "┤|├");
            Write(ConsoleColor.DarkGray, "─o┌┴───o");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───────┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "16 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└───┴┬┬┬┬┬┴───┤ LD├────┐┌─────┘");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "────┘o──┬───┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "15 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌────────");
            Write(ConsoleColor.White, "∧∧∧");
            Write(ConsoleColor.DarkGray, "──┤ FR├────┘└┐o┐┌──┘┌──────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "│┌──┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "14 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─────────────┴┬┬┬┴──────┴─┘├───┘");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "─┬┴┴┴┴┴┼┐┌┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "13 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "o");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───");
            Write(ConsoleColor.Red, "[─]");
            Write(ConsoleColor.DarkGray, "───");
            Write(ConsoleColor.Cyan, "┤[]├");
            Write(ConsoleColor.DarkGray, "────────────┐└─o┌─┘┌┤     ├┘└┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "12 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "V├─────");
            Write(ConsoleColor.DarkCyan, "┤|├");
            Write(ConsoleColor.DarkGray, "──────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o─────────┴───┘o─┴┤ INTE├──┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "11 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└┴────o");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───────┐└──────────────────┤ RNET├──┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "10 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "──────┘o──────┴────┬───");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "─────────┴┬┬┬┬┬┴──┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 9 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "├───");
            Write(ConsoleColor.Cyan, "┤[]├");
            Write(ConsoleColor.DarkGray, "───────┐o───┘┌───");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o───┬─");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "───────┐┌┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 8 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─────────┐┌───┘┌────┴──o├───");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "└───────┐o──┘│V ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 7 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "o─");
            Write(ConsoleColor.White, "∧∧∧");
            Write(ConsoleColor.DarkGray, "─────┘└────┴─o");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "────┐└──o└───────┐└────┴┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 6 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "──────────────────┘┌──o└───────");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "─┐├─");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "──┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 5 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└──────────");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o┴─────────────┐┌┘└──o┌──┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 4 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "o─");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┬─────");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "───────┘┌───");
            Write(ConsoleColor.DarkCyan, "┤|├");
            Write(ConsoleColor.DarkGray, "─");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "─────┤└─────┘┌─┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 3 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌─┘=┌─────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o───────┴───┐o────");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "───┴─");
            Write(ConsoleColor.Red, "[─]");
            Write(ConsoleColor.DarkGray, "──o└─┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 2 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└───┴────o└───────────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "└───");
            Write(ConsoleColor.Red, "[─]");
            Write(ConsoleColor.DarkGray, "──────");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "──────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 1 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "'-----------------------------------------------'       \n           \n");
            Write(ConsoleColor.Yellow, "\n   _      _             _          __    ___         _       ___ __  _ ____ \n  /_\\  __| |_ _____");
            Write(ConsoleColor.Yellow, " _ _| |_   ___ / _|  / __|___  __| |___  |_  )  \\/ |__  |\n / _ \\/ _` \\ V / -_) ' \\  _| / _ \\  ");
            Write(ConsoleColor.Yellow, "_| | (__/ _ \\/ _` / -_)  / / () | | / / \n/_/ \\_\\__,_|\\_/\\___|_||_\\__| \\___/_|    \\___\\___/");
            Write(ConsoleColor.Yellow, "\\__,_\\___| /___\\__/|_|/_/  \n");
            
            Console.ForegroundColor = color;
            Console.WriteLine();
        }

       private static void Write(ConsoleColor color, string text){
           Console.ForegroundColor = color;
           Console.Write(text);
       }
    }
}