
using System;

namespace AdventOfCode {

    class SplashScreen {

        public static void Show() {

            var color = Console.ForegroundColor;
            Write(ConsoleColor.Yellow, "\n  __   ____  _  _  ____  __ _  ____     __  ____     ___  __  ____  ____         \n / _\\ (    \\/");
            Write(ConsoleColor.Yellow, " )( \\(  __)(  ( \\(_  _)   /  \\(  __)   / __)/  \\(    \\(  __)        \n/    \\ ) D (\\ \\/ / ) _");
            Write(ConsoleColor.Yellow, ") /    /  )(    (  O )) _)   ( (__(  O )) D ( ) _)         \n\\_/\\_/(____/ \\__/ (____)\\_)__) (__)");
            Write(ConsoleColor.Yellow, "    \\__/(__)     \\___)\\__/(____/(____)  2017\n\n           ");
            Write(ConsoleColor.DarkGray, "|O|        Naughty |        Nice  |O|       \n           |O|  -------------------+------------------");
            Write(ConsoleColor.DarkGray, "-  |O|       \n           |O|  The Easter Bunny | encse  |O|       \n           |O|  szalai1 | Csaba");
            Write(ConsoleColor.DarkGray, " Okrona  |O|       \n           |O|  Marcell Endrey | uvegla  |O|       \n           |O|  jaksi | Ró");
            Write(ConsoleColor.DarkGray, "bert Bán  |O|       \n           |O|  abesto | vigoo  |O|       \n           ");
            Write(ConsoleColor.Gray, ".-----------------------------------------------.       \n           | ");
            Write(ConsoleColor.DarkGray, "┌─");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "────");
            Write(ConsoleColor.DarkCyan, "┤|├");
            Write(ConsoleColor.DarkGray, "─────┬─o┌────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "────────┐o─┬────┐o┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "25 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "│o─┐");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "─────");
            Write(ConsoleColor.DarkCyan, "┤|├");
            Write(ConsoleColor.DarkGray, "───┐├──┴───o└─────┐┌o└──┘┌──o└─┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "24 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└──┘└─────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o┬──o│=┌──────────┐┌┘└────┐├─────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "23 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "────────┐└┐└──┐└┐└─────┐┌──o│├─────┐└┴─────o ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "22 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└───────┐└─┤┌─");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "└─┴─");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "──┘├───┘├┴┴┴┴┴┤┌──");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "──┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "21 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌───────┘o─┘│V└──────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┌──┘o┬──┤     ├┴─o┌───┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "20 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "├───────────┴┘");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "─");
            Write(ConsoleColor.White, "∧∧∧");
            Write(ConsoleColor.DarkGray, "──┘└───┐├──┤     ├───┘o──┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "19 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└───o");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "────────┘┌─────────o│└─┐┤ SPC ├───");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "─┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "18 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌────┘┌");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o──────┴──");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "─────┐└─┐│┤ 700 ├─────┐┌┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "17 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─────┘└───────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┌┴┴┴┴┬──┬┴┴┴┤├┴┬┬┬┬┬┴─────┘└┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "16 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "──");
            Write(ConsoleColor.DarkCyan, "┤|├");
            Write(ConsoleColor.DarkGray, "─┬───────┘┤    ├──┤   ├│┌─────────────┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "15 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└────┐o┘┌───────┤    ├─");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┤   ├┘└───────┐┌────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "14 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───┐└──┘┌───");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "─┤8088├─┘┤   ├─────────┘│o───┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "13 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "├──┐└────┘┌────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "└┬┬┬┬┴┬─┴┬┬┬┴─────────o│┌───┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "12 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─o└──────┘");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───┘V└─┬┴┴┴┴┴┬──┐┌─────");
            Write(ConsoleColor.Red, "[─]");
            Write(ConsoleColor.DarkGray, "─┘├─┐o┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "11 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "──────┬┴┴┴┴┴┬──┴──┤     ├──┘└───");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "──┐o─┴o└─┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, "10 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o┤   EM├─────┤     ├───────");
            Write(ConsoleColor.Green, "|(");
            Write(ConsoleColor.DarkGray, "──┴──────┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 9 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌────┘┌┤   NM├─");
            Write(ConsoleColor.Cyan, "┤[]├");
            Write(ConsoleColor.DarkGray, "┤INTE ├───────────────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o─┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 8 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─────┴┤   CC├o");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "───┤RNET ├──");
            Write(ConsoleColor.Cyan, "┤[]├");
            Write(ConsoleColor.DarkGray, "────────┐└──┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 7 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌──────┤   OP├─┘o──┴┬┬┬┬┬┼────────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "┌───┐└───┤ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 6 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└─┐┌───┤     ├───");
            Write(ConsoleColor.Cyan, "┤[]├");
            Write(ConsoleColor.DarkGray, "────┘o┐");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "─────┘└─┐o┴───o│ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 5 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌─┘└o┌─┴┬┬┬┬┬┘o────");
            Write(ConsoleColor.Magenta, "oTo");
            Write(ConsoleColor.DarkGray, "─┬───┘└───────");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "└─┬────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 4 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└───┐└────────┐┌─┬─────┘");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "──────────┐└─┐└────┐ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 3 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "┌───┴───");
            Write(ConsoleColor.White, "∧∧∧");
            Write(ConsoleColor.DarkGray, "──o└┘V│");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "─────┘┌───┬────o└──┘┌───o│ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 2 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "| ");
            Write(ConsoleColor.DarkGray, "└───────────────┴┘└───");
            Write(ConsoleColor.Yellow, "*");
            Write(ConsoleColor.DarkGray, "o─┴──o└─────────┴────┘ ");
            Write(ConsoleColor.Gray, "|  ");
            Write(ConsoleColor.DarkGray, " 1 ");
            Write(ConsoleColor.Yellow, "**\n           ");
            Write(ConsoleColor.Gray, "'-----------------------------------------------'       \n           \n");
            
            Console.ForegroundColor = color;
            Console.WriteLine();
        }

       private static void Write(ConsoleColor color, string text){
           Console.ForegroundColor = color;
           Console.Write(text);
       }
    }
}